# Generated by Django 4.0.5 on 2022-06-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_journal_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
    ]
