# Generated by Django 4.0.5 on 2022-06-16 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 0, 30, 3, 351949), editable=False),
        ),
    ]
