# Generated by Django 4.0.5 on 2022-06-16 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 0, 33, 49, 472628, tzinfo=utc), editable=False),
        ),
    ]
